---
 - name: copy httpd configuration file
   copy: src=httpd.original dest=/etc/httpd/conf/httpd.conf

 - name: copy index.html file
   copy: src=index.html dest=/var/www/html
   notify:
    - restart apache

