---
- hosts: redhat-node
  become: yes
  remote_user: admin
  tasks:
   - name: install httpd package
     yum: name=httpd state=latest

   - name: copy httpd configuration file
     copy: src=/tmp/httpd.original dest=/etc/httpd/conf/httpd.conf

   - name: copy index.html file
     copy: src=/tmp/index.html dest=/var/www/html
     notify:
      - restart apache
   - name: start and enable httpd service
     service: name=httpd state=restarted enabled=yes
  
  handlers:
   - name: restart apache
     service: name=httpd state=restarted
