---
- hosts: all
  become: yes
  remote_user: admin
  tasks:
  - name: install apache on redhat
    yum:
      name: httpd
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install apache on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Start service httpd, if not started
    service:
      name: apache2
      state: started
    when: ansible_facts['os_family'] == "Debian"

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
    when: ansible_facts['os_family'] == "RedHat"

