---
- name: Download Tomcat8 
  hosts: redhat-node
  remote_user: admin
  become: yes
  tasks:
   - name: Create a Directory /opt/tomcat8
     file:
       path: /opt/tomcat8
       state: directory
       mode: 0755
   - name: Download Tomcat using get_url
     get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
       dest: /opt/tomcat8
       mode: 0755
   - name: Extract tomcat.tar.gz into /opt/tomcat8/tomcat
     unarchive:
       src: /opt/tomcat8/apache-tomcat-9.0.65.tar.gz
       dest: /opt/tomcat8
       remote_src: yes
