---
- hosts: redhat-node
  remote_user: admin
  become: yes
  tasks:
   - name: Show facts available on the system
     debug:
       var: ansible_facts
     when: ansible_facts['os_family'] == "Debian"
